let json = {
    'vocabulary': [{
        'word': 'Global emissions',
        'definition': 'The amount of greenhouse gas emissions that the world produces.'
    }, {
        'word': 'Greenhouse effect',
        'definition': "The greenhouse gasses that are being trapped in the atmosphere causing it to heat up."
    }, {
        'word': 'Atmospheric circulation',
        'definition': 'Large-scale movement of air & water around the world, '
    }, {
        'word': 'Fossil fuels',
        'definition': 'Fuels that are in the ground, such as Pterol, Oil, Coal, etc.'
    }, {
        'word': 'Nitrous oxide',
        'definition': 'A colourless gas with a sweetish odour.'
    }, {
        'word': 'Climate forcers',
        'definition': 'The things that cause the climate to increase or decrease warming.'
    }, {
        'word': 'Methane',
        'definition': 'One most destructive gasses to the ozone layer.'
    }, {
        'word': 'Tropospheric ozone',
        'definition': 'Ozone found closer to the ground. 20-30 parts per billion.'
    }, {
        'word': 'Solar output',
        'definition': 'The total amount of electrivity generated by the Solar Energy Facility.'
    }]
};
